import csv
from pathlib import Path

STOP_ID = "YOUR_STOP_ID" # enter your LTC stop_id here
STOP_TIMES = Path("stop_times.txt")
OUT_H = Path("tripset.h")

M_BITS = 65536   # 8KB bloom
K_HASHES = 3

def digits_only(s: str) -> str:
    return "".join(ch for ch in s if ch.isdigit())

def fnv1a_32(s: str) -> int:
    h = 2166136261
    for ch in s.encode("utf-8"):
        h ^= ch
        h = (h * 16777619) & 0xFFFFFFFF
    return h

def bloom_bit_indices(trip_digits: str):
    h1 = fnv1a_32(trip_digits)
    h2 = h1 ^ 0x9e3779b9
    for i in range(K_HASHES):
        yield (h1 + i * h2) % M_BITS

def main():
    if not STOP_TIMES.exists():
        raise SystemExit("stop_times.txt not found in this folder")

    trip_ids = set()

    with STOP_TIMES.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        if "trip_id" not in reader.fieldnames or "stop_id" not in reader.fieldnames:
            raise SystemExit(f"Unexpected header: {reader.fieldnames}")

        for row in reader:
            if row["stop_id"] == STOP_ID:
                tid = digits_only(row["trip_id"])
                if tid:
                    trip_ids.add(tid)

    print(f"Found {len(trip_ids)} trips that include stop_id={STOP_ID}")

    bits = bytearray(M_BITS // 8)

    def set_bit(bi: int):
        bits[bi >> 3] |= (1 << (bi & 7))

    for tid in trip_ids:
        for bi in bloom_bit_indices(tid):
            set_bit(bi)

    OUT_H.write_text(
        "// Auto-generated by make_tripset.py (FNV1a/double-hash to match ESP32)\n"
        "#pragma once\n"
        "#include <stdint.h>\n"
        f"#define BLOOM_M_BITS {M_BITS}\n"
        f"#define BLOOM_K_HASHES {K_HASHES}\n"
        f"static const uint8_t TRIP_BLOOM[{len(bits)}] PROGMEM = {{\n"
        + ",\n".join(
            "  " + ", ".join(str(b) for b in bits[i:i+16])
            for i in range(0, len(bits), 16)
        )
        + "\n};\n",
        encoding="utf-8"
    )

    print(f"Wrote {OUT_H} ({len(bits)} bytes)")

if __name__ == "__main__":
    main()
